//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationFormGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegistrationFormGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to বরিশাল বিশ্ববিদ্যালয়ে  ২০১৬-১৭ শিক্ষাবর্ষে উল্লেখিত বিভাগ এর ব্যাচেলর অফ বিজনেস এডমিনিস্ট্রেশন (বি. বি. এ.) পাঠক্রমে উপর্যুক্ত  শিক্ষার্থীর ভর্তি প্রক্রিয়া সম্পন্ন হয়েছে এবং একজন শিক্ষার্থী হিসেবে বিশ্ববিদ্যালয়ে তাকে নিবন্ধিত করা হয়েছে।.
        /// </summary>
        internal static string BengaliTextAccountingAndInformation {
            get {
                return ResourceManager.GetString("BengaliTextAccountingAndInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to বরিশাল বিশ্ববিদ্যালয়ে  ২০১৬-১৭ শিক্ষাবর্ষে উল্লেখিত বিভাগ এর ব্যাচেলর অফ আর্টস (বি এ) পাঠক্রমে উপর্যুক্ত  শিক্ষার্থীর ভর্তি প্রক্রিয়া সম্পন্ন হয়েছে এবং একজন শিক্ষার্থী হিসেবে বিশ্ববিদ্যালয়ে তাকে নিবন্ধিত করা হয়েছে।.
        /// </summary>
        internal static string BengaliTextBangla {
            get {
                return ResourceManager.GetString("BengaliTextBangla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to বরিশাল বিশ্ববিদ্যালয়ে  ২০১৬-১৭ শিক্ষাবর্ষে উল্লেখিত বিভাগ এর ব্যাচেলর অফ সাইন্স (বি এস) পাঠক্রমে উপর্যুক্ত  শিক্ষার্থীর ভর্তি প্রক্রিয়া সম্পন্ন হয়েছে এবং একজন শিক্ষার্থী হিসেবে বিশ্ববিদ্যালয়ে তাকে নিবন্ধিত করা হয়েছে।.
        /// </summary>
        internal static string BengaliTextBotany {
            get {
                return ResourceManager.GetString("BengaliTextBotany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to বরিশাল বিশ্ববিদ্যালয়ে  ২০১৬-১৭ শিক্ষাবর্ষে উল্লেখিত বিভাগ এর ব্যাচেলর অফ ল (এল এল বি) পাঠক্রমে উপর্যুক্ত  শিক্ষার্থীর ভর্তি প্রক্রিয়া সম্পন্ন হয়েছে এবং একজন শিক্ষার্থী হিসেবে বিশ্ববিদ্যালয়ে তাকে নিবন্ধিত করা হয়েছে।.
        /// </summary>
        internal static string BengaliTextLaw {
            get {
                return ResourceManager.GetString("BengaliTextLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to বরিশাল বিশ্ববিদ্যালয়ে  ২০১৬-১৭ শিক্ষাবর্ষে উল্লেখিত বিভাগ এর ব্যাচেলর অফ সাইন্স (বি এস) পাঠক্রমে উপর্যুক্ত  শিক্ষার্থীর ভর্তি প্রক্রিয়া সম্পন্ন হয়েছে এবং একজন শিক্ষার্থী হিসেবে বিশ্ববিদ্যালয়ে তাকে নিবন্ধিত করা হয়েছে।.
        /// </summary>
        internal static string BengaliTextMathematics {
            get {
                return ResourceManager.GetString("BengaliTextMathematics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to বরিশাল বিশ্ববিদ্যালয়ে  ২০১৬-১৭ শিক্ষাবর্ষে উল্লেখিত বিভাগ এর ব্যাচেলর অফ সোশ্যাল সাইন্স (বি এস এস) পাঠক্রমে উপর্যুক্ত  শিক্ষার্থীর ভর্তি প্রক্রিয়া সম্পন্ন হয়েছে এবং একজন শিক্ষার্থী হিসেবে বিশ্ববিদ্যালয়ে তাকে নিবন্ধিত করা হয়েছে।.
        /// </summary>
        internal static string BengaliTextSociology {
            get {
                return ResourceManager.GetString("BengaliTextSociology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The above mentioned student is admitted in the Bachelor of Business Administration (B.B.A.) Program of mentioned Department in the 2016-17 academic year and he is registered as a student of the university..
        /// </summary>
        internal static string EnglishTextAccountingAndInformation {
            get {
                return ResourceManager.GetString("EnglishTextAccountingAndInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The above mentioned student is admitted in the Bachelor of Bachelor of Arts (B.A.) Program of mentioned Department in the 2016-17 academic year and he is registered as a student of the university..
        /// </summary>
        internal static string EnglishTextBangla {
            get {
                return ResourceManager.GetString("EnglishTextBangla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The above mentioned student is admitted in the Bachelor of Science (B.S.) Program of mentioned Department in the 2016-17 academic year and he is registered as a student of the university..
        /// </summary>
        internal static string EnglishTextBotany {
            get {
                return ResourceManager.GetString("EnglishTextBotany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The above mentioned student is admitted in the Bachelor of Law (L.L.B.) Program of mentioned Department in the 2016-17 academic year and he is registered as a student of the university..
        /// </summary>
        internal static string EnglishTextLaw {
            get {
                return ResourceManager.GetString("EnglishTextLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The above mentioned student is admitted in the Bachelor of Science (B.S.) Program of mentioned Department in the 2016-17 academic year and he is registered as a student of the university..
        /// </summary>
        internal static string EnglishTextMathematics {
            get {
                return ResourceManager.GetString("EnglishTextMathematics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The above mentioned student is admitted in the Bachelor of Social Science (B.S.S.) Program of mentioned Department in the 2016-17 academic year and he is registered as a student of the university..
        /// </summary>
        internal static string EnglishTextSociology {
            get {
                return ResourceManager.GetString("EnglishTextSociology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ExcelFormet {
            get {
                object obj = ResourceManager.GetObject("ExcelFormet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;  CERTIFICATE OF REGISTRATION&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;table align=&quot;right&quot; width=&quot;30%&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;1&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td width=&quot;250&quot; valign=&quot;top&quot;&gt;
        ///                    &lt;p&gt;
        ///                        রেজিস্ট্রেশন নম্বর&lt;br /&gt;(REGISTRATION NO.)
        ///                    &lt;/p&gt;
        ///                &lt;/td&gt;
        ///                &lt;td colspan=&quot;3&quot; width=&quot;70&quot; valign=&quot;top&quot;&gt;
        ///                    &lt;p id=&quot;R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Html_Template {
            get {
                return ResourceManager.GetString("Html_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SolaimanLipi {
            get {
                object obj = ResourceManager.GetObject("SolaimanLipi", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
